### ISSUE TITLE
assets 與 scripts 拆分設計

### ISSUE THREAD

**Issue by eastmoon** [neowu/frontend-demo-project#1]
# ◎ assets 與 scripts 拆分 

### 1. 合併圖片腳本 SpritesmithPlugin

雪花圖片合併方式，使得資源檔會指向單一檔案夾下，並且輸出至統一位置。

因此圖檔並不適合散落於各檔案夾內。

### 2. Skin 設計方式

目前專案中，依據用戶需求可更換頁面整體Style，因此Style會依據skin的設計概念區分，並不會完全依照項目、模組方式區分。

因此style設定不適合散落於各檔案夾內。

## § assets 問題與修改

目前的assets雖依據用圖區分，但並沒有依據專案項目 ( Page ) 適度區分局部用圖的樣式、圖檔；這部分仍需與前端程式設計師討論。

**Comment by neowu** [comment]
discussed in email
