### ISSUE TITLE
page 設計問題

### ISSUE THREAD

**Issue by eastmoon** [neowu/frontend-demo-project#2]
# ◎ page 設計問題

目前專案對於 page 設計相似此專案；於專案內的 Webpack 亦有相同的執行原點。
但與前端部門討論後，有下項討論：

## Quest：page應有幾層？

目前專案中，除一項目外，皆只有一個進入點。
> pages/[item name]/index.jsx

而特例，則第一層是用於整理共通內容之用。

## Ans： 

討論結過，有以下兩個設計問題

### 1、如何使用頁面

依據設計稿，目前多頁面間使用主從關係的iframe，還有直接切換的page redirection。
若頁面層級過深會導致頁面過多而溝通困難。

### 2、設計Module

在 Multi-page software architecture design 中規範到
> pages -> modules -> components
* pages，頁面，Webpack專案建立以頁面為進入點；一個單一頁面會擁有複數的modules、components組成。
* modules，模組，一個模組式由複數的modules、components組成。
* components，單元，一個單元為一個React.Component；若其繪製的元素(Elements)層級過深，應注意是否需重新拆分單元。

其設計目的即是取代多層頁面的不必要性，改用module取代page，避免輸出頁面。

**Comment by neowu** [comment]
will discuss in email
