### ISSUE TITLE
ESLint : Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style

### ISSUE THREAD

**Issue by eastmoon** [neowu/frontend-demo-project#3]
# ESLint 錯誤

## 原因

因為作業系統的段行格式錯誤，導致ESlint無法正確執行。

## 解決方案

[enforce consistent linebreak style (linebreak-style)](http://eslint.org/docs/rules/linebreak-style)

## 結果

實際改寫ESLint檔案也無法解決此問題，對此煩請應如何處理。
```
rules: {
    ...
    "linebreak-style": ["error", "windows"],
    ...
}
```
由於目前開發人員多使用Windows環境，這會使得ESLint難以運作。

**Comment by eastmoon** [comment]
找到解決方式
[github issues : eslint-loader with WebPack 2.2](https://github.com/MoOx/eslint-loader/issues/148)

原文說明
『The --fix option on the command line can automatically fix some of the problems reported by this rule.』

雖然知道要執行 fix，但沒有文件說明如何在 Webpack 中設定。
在此討論中找到設定方式，在options中設定 fix。

```
options: {
                ...
                failOnWarning: true,
                failOnError: true,
                fix: true,
                cache: true
}
```

**Comment by neowu** [comment]
discussed thru email
