### ISSUE TITLE
Imports should be sorted alphabetically  sort-imports

### ISSUE THREAD

**Issue by eastmoon** [neowu/frontend-demo-project#4]
# ESLint 錯誤 

## 原因

今日測試新版本後，因個人用fork使用另外開版本修正src格式，在逐一修補更新與檢閱時，發現此議題。

## 解決方案

[Import Sorting (sort-imports)](http://eslint.org/docs/2.0.0/rules/sort-imports)

## 議題

在比對新版與舊版的ESLint後，在下知道設定了import迴避大小寫檢查。
這部份就順便提個議題？

基於個人習慣，在C#、Java等語言會有以下習慣。
* 引入類別、類別宣告皆以大寫開頭。
* 變數、函述宣告皆以小寫開頭。
* 傳入參數、區域變數，會依語言規範前綴符號、字詞以供區別變數的生命週期、影響範圍。

不知道是否要訂妥一個宣告與引用規範？

**Comment by neowu** [comment]
let's remove sort-imports rule. since the tool (Intellij/Atom) doesn't support it well, and it makes sense to group imports by module (external/internal) not by alphabet
